### ISSUE TITLE
Cannot reproduce the paper results with some datasets 

### ISSUE THREAD

**Issue by LittleTigger-alpha** [cure-lab/LTSF-Linear#44]
I run the scripts in your code. But I cannot reproduce the paper results, for example ETTh2. Is there something wrong？

![image](https://user-images.githubusercontent.com/42534251/219934695-e4f21a9e-68be-45cd-8b26-2e55f5601b9d.png)

**Comment by mixiancmx** [comment]
Your results of Linear and NLinear are very close and sometimes better than we claimed in the paper. It might be caused by some difference in the environment, i.e, cuda version, torch, gpu. 

For the reproduced results of DLinear, you can refer to this issue.
https://github.com/cure-lab/LTSF-Linear/issues/39
