### ISSUE TITLE
How to predict a single target with multivariables?

### ISSUE THREAD

**Issue by cybisolated** [cure-lab/LTSF-Linear#56]
Dear authors, I found that the implement of all linear models aligns the input channels and output channels. However, I need to predict a  single target varibale with multivariate inputs, and how should I modify the code? I think an extra `nn.Linear` module is required, and where should I insert? Thanks for your kind reply!

**Comment by mixiancmx** [comment]
Hi, the hyperparameter "feature=MS" might meet your requirement. But since linear didn't consider the relation between variates, you can add a linear layer to merge the input information. You can choose to place the linear layer before or after the original linear layer based on validation performance. For example add a linear layer that is M->1 in lines 33-34 of Linear.py

**Comment by cybisolated** [comment]
Thanks for your response! I have tried your DLinear model on my task and achieved good results, though the relation between varaites were not considered. I will think about your solution and try to extract potential multivariate relations. Thanks again for your reply and your great contributions!

**Comment by baniasbaabe** [comment]
@cybisolated can you add a working example for multivariable input if possible? :)

**Comment by cybisolated** [comment]
@baniasbaabe Actually, as the author mentioned, taking NLinear as an example, I just add a linear module `nn.Linear(M, target_size)`  between line 86 and 87. This can extract feature relations to some extent but maybe not enough. I think a hidden layer `nn.Linear(M, d_model) => nn.Linear(d_model, target_size)` can be added to enhance the fitting ability of model.
