### ISSUE TITLE
比较的输入长度问题

### ISSUE THREAD

**Issue by huangsiyuan924** [cure-lab/LTSF-Linear#73]
您好，我发现Linears的输入长度是336，而formers的输入长度都是96，这样得到的结果是否公平？

**Comment by ailingzengzzz** [comment]
Hi @huangsiyuan924,

As shown in Fig.4 of our [paper](https://arxiv.org/pdf/2205.13504.pdf), we study the impact of input look-back window sizes. Existing Transformer-based models’ performance deteriorates or stays stable when the look-back window size increases. To make a fair comparison with previous Transformers and maintain good performance, existing Transformers tend to use the same 96 as the look-back window size. However, as the task of "long-term time series forecasting" is not well-defined, whether the input length can only be as proposed in the original work is open to discussion. 
On the one hand, a linear layer with a few learnable parameters (the parameter is T*L) will perform better with a longer input size. To show the potential of the proposed linear model, we compare it with better performance compared with the shorter input size. On the other hand, we compare with Transformer with their better performance (96 as input length instead of 336 with worse performance).

**Comment by huangsiyuan924** [comment]
> Hi @huangsiyuan924,
> 
> As shown in Fig.4 of our [paper](https://arxiv.org/pdf/2205.13504.pdf), we study the impact of input look-back window sizes. Existing Transformer-based models’ performance deteriorates or stays stable when the look-back window size increases. To make a fair comparison with previous Transformers and maintain good performance, existing Transformers tend to use the same 96 as the look-back window size. However, as the task of "long-term time series forecasting" is not well-defined, whether the input length can only be as proposed in the original work is open to discussion. On the one hand, a linear layer with a few learnable parameters (the parameter is T*L) will perform better with a longer input size. To show the potential of the proposed linear model, we compare it with better performance compared with the shorter input size. On the other hand, we compare with Transformer with their better performance (96 as input length instead of 336 with worse performance).

ok, thank you for your reply!
